services:
  secret-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: secret-agent
    networks:
      - sec-net
    environment:
      - SECRET_AGENT_KMS_URL=http://kms-service:8080
      - SECRET_AGENT_KMS_SECRETS_PATH=/api/v1/agent/credentials/issue
      - SECRET_AGENT_CLIENT_ID=auth-service
      - SECRET_AGENT_SOCKET_PATH=/var/run/agent-sockets/agent.sock
      - SECRET_AGENT_SA_TOKEN_PATH=/run/secrets/sa_token
      - RUST_LOG=info
    secrets:
      - sa_token
    volumes:
      - socket-data:/var/run/agent-sockets

secrets:
  sa_token:
    file: ./secrets/.mock_sa_token

volumes:
  socket-data:
    name: secret_agent_sockets

networks:
  sec-net:
    name: kms_sec-net
    external: true
