FROM rust:1-slim

# Instalacja zależności systemowych (jeśli potrzebne)
RUN apt-get update && apt-get install -y pkg-config libssl-dev & rm -rf /var/lib/apt/lists/*

# Instalacja cargo-watch
RUN cargo install cargo-watch

WORKDIR /app

# Domyślne polecenie uruchamiające obserwatora
CMD ["cargo", "watch", "-x", "run"]